splash = false

wallpaper {
    monitor = HDMI-A-2
    path = ~/wallpapers/yosemite-catppuccin.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = ~/wallpapers/yosemite-catppuccin.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/wallpapers/yosemite-catppuccin.png
    fit_mode = cover
}
