splash = false

wallpaper {
    monitor = HDMI-A-2
    path = ~/wallpapers/dead-robot-gruvbox.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = ~/wallpapers/dead-robot-gruvbox.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/wallpapers/dead-robot-gruvbox.jpg
    fit_mode = fill
}
