splash = false

wallpaper {
    monitor = HDMI-A-2
    path = ~/wallpapers/borges-colorized.png
    fit_mode = fill
}

wallpaper {
    monitor = DP-6
    path = ~/wallpapers/borges-colorized.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/wallpapers/borges-colorized.png
    fit_mode = fill
}
