#!/bin/bash

THEME=$1

# hyprland, waybar and rofi
cp "$HOME/.config/hypr/themes/$THEME.conf" ~/.config/hypr/current-theme.conf

# kitty
cp "$HOME/.config/kitty/$THEME.conf" ~/.config/kitty/colorscheme.conf

# reload kitty theme
kill -SIGUSR1 $(pgrep kitty)

# zsh
cp "$HOME/.config/zsh/$THEME.sh" ~/.config/zsh/prompt.sh

# neovim
echo "$THEME" >~/.config/nvim/colorscheme

# gtk gsettings
gsettings set org.gnome.desktop.interface gtk-theme $1
gsettings set org.gnome.desktop.wm.preferences theme $1

gsettings set org.gnome.desktop.interface gtk-theme $1
gsettings set org.gnome.desktop.wm.preferences theme $1

# icon theme
gsettings set org.gnome.desktop.interface icon-theme $1

# gtk 2.0
sed -i -E 's/(gtk-theme-name=")(.*)(")/\1'$1'\3/g' ~/.gtkrc-2.0

# gtk 3.0
sed -i -E 's/(gtk-theme-name=)(.*)/\1'$1'/g' ~/.config/gtk-3.0/settings.ini

# gtk 4.0
rm -r ~/.config/gtk-4.0/* 2>/dev/null
cp -r /usr/share/themes/$1/gtk-4.0/* ~/.config/gtk-4.0/ 2>/dev/null || cp -r ~/.themes/$1/gtk-4.0/* ~/.config/gtk-4.0/ 2>/dev/null || cp -r ~/.config/themes/gtk/$1/gtk-4.0/* ~/.config/gtk-4.0/ 2>/dev/null
