$menu = rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/rofi/gruvbox/launcher.rasi
$wallpaper = hyprpaper --config ~/.config/hypr/wallpapers/gruvbox.conf
$bar = ~/.config/waybar/gruvbox/launch.sh
$swaync = swaync -c ~/.config/swaync/gruvbox/config.json -s ~/.config/swaync/gruvbox/style.css

general {
  col.inactive_border = rgba(d4be98ff)
  col.active_border = rgba(a89984ff)
}

