$menu = rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/rofi/tokyonight/launcher.rasi
$wallpaper = hyprpaper --config ~/.config/hypr/wallpapers/tokyonight.conf
$bar = ~/.config/waybar/tokyonight/launch.sh
$swaync = swaync -c ~/.config/swaync/tokyonight/config.json -s ~/.config/swaync/tokyonight/style.css

general {
  col.inactive_border = rgba(3a4f5fff)
  col.active_border = rgba(9aa5ceff)
}

