$menu = rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/rofi/catppuccin-latte/launcher.rasi
$wallpaper = hyprpaper --config ~/.config/hypr/wallpapers/catppuccin-latte.conf
$bar = ~/.config/waybar/catppuccin-latte/launch.sh
$swaync = swaync -c ~/.config/swaync/catppuccin-latte/config.json -s ~/.config/swaync/catppuccin-latte/style.css

general {
  col.inactive_border = rgba(dc8a78ff)
  col.active_border = rgba(8839efff)
}

